# Generated by Django 4.1.13 on 2023-12-13 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("a64e91d1-e909-4de1-87bd-8391b90bc72d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
